service: node-serverless-app

provider: 
  name: aws 
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: eu-central-1 
  environment:
    MONDAY_TOKEN: ${env:MONDAY_TOKEN}

functions: 
  app: 
    handler: app.handler 
    events: 
      - http:
          path: /monday/unfurl
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin